import { builtinModules } from 'node:module';
import tailwindcss from '@tailwindcss/vite';
import { createLogger, defineConfig } from 'vite';

const banner = `/*! THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN — see the plugin repository for source. */`;

// Silence Vite's "outDir is the same directory as root" warning. We intentionally
// emit main.js into the plugin folder (which Obsidian loads directly) and guard
// against clobbering sources with `emptyOutDir: false`.
const logger = createLogger();
const origWarn = logger.warn.bind(logger);
logger.warn = (msg, opts) => {
  if (typeof msg === 'string' && msg.includes('build.outDir must not be the same directory')) {
    return;
  }
  origWarn(msg, opts);
};

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';

  return {
    customLogger: logger,
    plugins: [tailwindcss()],
    build: {
      lib: {
        entry: 'src/main.ts',
        formats: ['cjs'],
        fileName: () => 'main.js',
        cssFileName: 'styles',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          /^@lezer\//,
          ...builtinModules,
          ...builtinModules.map((m) => `node:${m}`),
        ],
        output: {
          exports: 'default',
          banner,
        },
      },
      target: 'es2022',
      // External source maps (`main.js.map`, `styles.css.map`) so we can
      // ship them alongside the built assets on GitHub releases without
      // bloating the main bundle with inline maps.
      sourcemap: true,
      minify: isProd,
      emptyOutDir: false,
      outDir: '.',
      copyPublicDir: false,
    },
  };
});
